---
- name: Reset password
  hosts: all
  gather_facts: no

  vars: 
    - default_password: "consored"
  tasks:
    - name: Wait 300 seconds until hosts respond
      ansible.builtin.wait_for_connection:
        timeout: 300
    - name: Ensure Administrator password is set
      ansible.windows.win_user:
        name: Administrator
        password: "{{ default_password }}"
    - name: Ensure Administrator password is set
      ansible.windows.win_user:
        name: tnoadmin
        password: "{{ default_password }}"
