services:
  mongodb_container:
    image: docker.io/mongo:latest
    container_name: mongo_soarca_stack
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootpassword"
    networks:
      - db-net
    volumes:
      - type: volume
        source: mongodb_data_container
        target: /data/db

  soarca:
    image: docker.io/cossas/soarca:development
    container_name: soarca_server
    environment:
      PORT: 8080
      SOARCA_ALLOWED_ORIGINS: "*"
      GIN_MODE: "release"
      MONGODB_URI: "mongodb://mongodb_container:27017"
      DATABASE_NAME: "soarca"
      DB_USERNAME: "root"
      DB_PASSWORD: "rootpassword"
      PLAYBOOK_API_LOG_LEVEL: trace
      DATABASE: "true"
      LOG_GLOBAL_LEVEL: "trace"
      LOG_MODE: "production"
      LOG_FILE_PATH: ""
      LOG_FORMAT: "json"
      ENABLE_FINS: false
      HTTP_SKIP_CERT_VALIDATION: false
    networks:
      - db-net
      - mqtt-net
      - soarca-net
    ports:
      - 0.0.0.0:8080:8080
    depends_on:
      - mongodb_container
  
  soarca-gui:
    image: docker.io/cossas/soarca-gui:development
    container_name: soarca_gui
    environment:
      SOARCA_URI: "http://soarca_server:8080"
    networks:
      - soarca-net
    ports:
      - 0.0.0.0:8081:8081
    depends_on:
      - soarca

networks:
  db-net:
  mqtt-net:
  soarca-net:


volumes:
  mongodb_data_container:


