---
- name: DOCKER | Install docker 
  hosts: soarca
  become: true
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
