---
- name: Wait 300 seconds
  ansible.builtin.wait_for_connection:
    timeout: 300

- name: Create folder
  ansible.windows.win_file:
    path: C:\share\
    state: directory

- name: Add public company share
  ansible.windows.win_share:
    name: company
    description: Company share
    path: C:\share\
    list: true
    full: DomainAdminsTNO
    change: TNOrw
